### ISSUE TITLE
Error during test

### ISSUE THREAD

**Issue by fastmode** [learn-co-students/react-rendering-lab-v-000#184]
Received an error during test not allowing me to run any of them.

```
/Users/admin/Dev/code/labs/react/react-rendering-lab-v-000/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328
        throw e;
        ^

Error: Couldn't find preset "es2015" relative to directory "/Users/admin/Dev/code/labs/react/react-rendering-lab-v-000"
    at /Users/admin/Dev/code/labs/react/react-rendering-lab-v-000/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/admin/Dev/code/labs/react/react-rendering-lab-v-000/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/admin/Dev/code/labs/react/react-rendering-lab-v-000/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/admin/Dev/code/labs/react/react-rendering-lab-v-000/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/admin/Dev/code/labs/react/react-rendering-lab-v-000/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/Users/admin/Dev/code/labs/react/react-rendering-lab-v-000/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/admin/Dev/code/labs/react/react-rendering-lab-v-000/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/admin/Dev/code/labs/react/react-rendering-lab-v-000/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /Users/admin/Dev/code/labs/react/react-rendering-lab-v-000/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/admin/Dev/code/labs/react/react-rendering-lab-v-000/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/Users/admin/Dev/code/labs/react/react-rendering-lab-v-000/node_modules/mocha/lib/mocha.js:514:10)
    at Object.<anonymous> (/Users/admin/Dev/code/labs/react/react-rendering-lab-v-000/node_modules/mocha/bin/_mocha:480:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

labs/react/react-rendering-lab-v-000  master ✗                       2d ⚑
▶ /Users/admin/.rvm/gems/ruby-2.3.3/gems/learn-test-2.5.1/lib/learn_test/strategies/mocha.rb:42:in `results': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/admin/.rvm/gems/ruby-2.3.3/gems/learn-test-2.5.1/lib/learn_test/reporter.rb:47:in `report'
	from /Users/admin/.rvm/gems/ruby-2.3.3/gems/learn-test-2.5.1/lib/learn_test/reporter.rb:13:in `report'
	from /Users/admin/.rvm/gems/ruby-2.3.3/gems/learn-test-2.5.1/lib/learn_test/runner.rb:44:in `report_and_clean'
	from /Users/admin/.rvm/gems/ruby-2.3.3/gems/learn-test-2.5.1/lib/learn_test/runner.rb:21:in `block in run'
	from /Users/admin/.rvm/gems/ruby-2.3.3/gems/learn-test-2.5.1/lib/learn_test/runner.rb:20:in `fork'
	from /Users/admin/.rvm/gems/ruby-2.3.3/gems/learn-test-2.5.1/lib/learn_test/runner.rb:20:in `run'
	from /Users/admin/.rvm/gems/ruby-2.3.3/gems/learn-test-2.5.1/bin/learn-test:64:in `<top (required)>'
	from /Users/admin/.rvm/gems/ruby-2.3.3/bin/learn-test:22:in `load'
	from /Users/admin/.rvm/gems/ruby-2.3.3/bin/learn-test:22:in `<main>'
	from /Users/admin/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/admin/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```
I followed the resolution from a previous issues in order to run and pass this lab.
Resolution:  https://github.com/learn-co-students/react-rendering-lab-v-000/issues/176

**Comment by pbortnick** [comment]
Potential fix is editing package.json to look like this:

`{
  "name": "react-component-mounting-and-unmounting-lab",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "enzyme": "^2.7.0",
    "jsdom": "^9.9.1",
    "mocha": "^3.2.0",
    "react-scripts": "^1.0.7",
    "react-test-renderer": "^15.6.2",
    "webpack": "^2.2.0",
    "webpack-dev-server": "^1.16.2"
  },
  "dependencies": {
    "babel-core": "^6.22.1",
    "babel-loader": "^7.1.2",
    "babel-preset-airbnb": "^2.1.1",
    "babel-preset-env": "^1.6.0",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-react": "^6.22.0",
    "babel-preset-stage-0": "^6.22.0",
    "chai": "^3.5.0",
    "expect": "^21.2.1",
    "mocha-multi": "^1.0.0",
    "react": "^15.6.2",
    "react-dom": "^15.6.2",
    "sinon": "^1.17.7"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "mocha -w test/helpers.js test/*.js",
    "dev:hot": "webpack-dev-server --hot --inline --progress --colors --watch --display-error-details --display-cached --content-base ./",
    "test:watch": "npm run test -- --watch",
    "eject": "react-scripts eject"
  }
}`
